workflows:
  vorxy-code-editor:
    name: Vorxy Code Editor
    max_build_duration: 10
    environment:
      flutter: 3.47.2
    scripts:
      - name: Clean build
        script: |
          rm -rf build
          rm -rf .dart_tool
          rm -rf android/.gradle
          rm -rf android/app/build
      - name: Install dependencies
        script: flutter pub get
      - name: Generate icons
        script: |
          if [ -f "pubspec.yaml" ] && grep -q "flutter_launcher_icons" pubspec.yaml; then
            dart run flutter_launcher_icons || true
          fi
      - name: Build APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
