class AppConstants {
  static const String appName = 'Vorxy Code Editor';
  static const String version = '1.0.0';
  static const String developer = 'GOSTOWN Co.';
  static const String telegramChannel = 'https://t.me/VorxyCodeEditor';
  static const String telegramChat = 'https://t.me/VorxyCodeEditorChat';
  static const String supportEmail = 'vorxygtn@mail.ru';

  static const List<Map<String, String>> supportedLanguages = [
    {'code': 'ru', 'name': 'Русский', 'flag': '🇷🇺'},
    {'code': 'en', 'name': 'English', 'flag': '🇬🇧'},
    {'code': 'uk', 'name': 'Українська', 'flag': '🇺🇦'},
    {'code': 'es', 'name': 'Español', 'flag': '🇪🇸'},
    {'code': 'fr', 'name': 'Français', 'flag': '🇫🇷'},
    {'code': 'de', 'name': 'Deutsch', 'flag': '🇩🇪'},
    {'code': 'zh', 'name': '简体中文', 'flag': '🇨🇳'},
    {'code': 'ja', 'name': '日本語', 'flag': '🇯🇵'},
    {'code': 'ko', 'name': '한국어', 'flag': '🇰🇷'},
    {'code': 'pt', 'name': 'Português', 'flag': '🇵🇹'},
    {'code': 'it', 'name': 'Italiano', 'flag': '🇮🇹'},
    {'code': 'ar', 'name': 'العربية', 'flag': '🇸🇦'},
    {'code': 'hi', 'name': 'हिन्दी', 'flag': '🇮🇳'},
  ];

  static const Map<String, Map<String, String>> translations = {
    'ru': {
      'app_name': 'Vorxy Code Editor',
      'settings': 'Настройки',
      'languages': 'Языки программирования',
      'editor': 'Редактор',
      'files': 'Файлы',
      'output': 'Вывод',
      'errors': 'Ошибки',
      'terminal': 'Терминал',
      'dark_theme': 'Тёмная тема',
      'auto_save': 'Автосохранение',
      'font_size': 'Размер шрифта',
      'tabulation': 'Табуляция',
      'support': 'Поддержка',
      'telegram_channel': 'Telegram-канал',
      'telegram_chat': 'Чат Telegram',
      'report_bug': 'Сообщить об ошибке',
      'legal': 'Юридическая информация',
      'privacy_policy': 'Политика конфиденциальности',
      'terms': 'Пользовательское соглашение',
      'about': 'О приложении',
      'name': 'Название',
      'version': 'Версия',
      'developer': 'Разработчик',
      'exit': 'Выйти',
      'language': 'Язык интерфейса',
      'save': 'Сохранить',
      'run': 'Запустить',
      'output_ready': 'Готов к выполнению',
      'executing': 'Выполнение...',
      'connected': 'Подключено',
      'disconnected': 'Отключено',
      'no_internet': 'Нет интернета',
      'error': 'Ошибка',
      'success': 'Успешно',
      'cancel': 'Отмена',
      'close': 'Закрыть',
      'search': 'Поиск',
      'replace': 'Заменить',
      'replace_all': 'Заменить все',
      'find': 'Найти',
      'format': 'Форматировать',
      'undo': 'Отменить',
      'redo': 'Повторить',
      'loading': 'Загрузка...',
      'home': 'Главная',
      'clone': 'Клонировать',
      'commit_push': 'Commit & Push',
      'git': 'Git',
      'web_preview': 'Web Preview',
      'no_servers': 'Нет доступных серверов',
      'refresh': 'Обновить',
      'delete': 'Удалить',
      'rename': 'Переименовать',
      'create_folder': 'Создать папку',
      'create_file': 'Создать файл',
      'file_actions': 'Действия для',
      'opening': 'Открытие',
      'in_development': 'в разработке',
      'copy': 'Копировать',
      'clear': 'Очистить',
      'copying': 'Копирование в разработке',
      'clearing': 'Очистка вывода в разработке',
      'formatting': 'Форматирование кода в разработке',
      'searching': 'Поиск в разработке',
      'find_replace': 'Поиск и замена',
      'replace_hint': 'Заменить на...',
      'find_hint': 'Найти...',
      'matches_found': 'совпадений',
      'replace_one': 'Заменить',
      'replace_all_btn': 'Заменить все',
      'cancel_replace': 'Отменить замену',
      'undo_hint': 'Отменить (Ctrl+Z)',
      'redo_hint': 'Повторить (Ctrl+Y)',
      'done': 'Готово',
      'select_language': 'Выберите язык / Select language',
      'language_changed': 'Язык изменён на',
      'file_saved': 'Файл сохранён',
      'file_saved_msg': 'Файл сохранён',
      'clone_success': 'Репозиторий успешно клонирован',
      'clone_error': 'Ошибка клонирования',
      'commit_error': 'Ошибка коммита',
      'push_success': 'Код отправлен в репозиторий',
      'push_error': 'Ошибка пуша',
      'clone_first': 'Сначала клонируйте репозиторий',
      'git_not_installed': 'Git не установлен на устройстве',
      'code_ready': 'Готов к выполнению',
      'executing_code': 'Выполнение...',
      'execution_success': 'Программа выполнена успешно',
      'execution_error': 'Ошибка выполнения',
      'html_ready': 'HTML код готов к просмотру в Web Preview',
      'cloud_error': 'Ошибка сервера',
      'connection_error': 'Ошибка подключения',
      'unknown_error': 'Неизвестная ошибка',
      'line': 'Строк',
      'language_label': 'Язык:',
      'output_label': 'Вывод:',
      'general': 'Общие',
      'about_app': 'О приложении',
      'privacy_title': 'Политика конфиденциальности',
      'terms_title': 'Пользовательское соглашение',
      'light_theme': 'Светлая тема',
    },
    'en': {
      'app_name': 'Vorxy Code Editor',
      'settings': 'Settings',
      'languages': 'Programming Languages',
      'editor': 'Editor',
      'files': 'Files',
      'output': 'Output',
      'errors': 'Errors',
      'terminal': 'Terminal',
      'dark_theme': 'Dark Theme',
      'light_theme': 'Light Theme',
      'auto_save': 'Auto Save',
      'font_size': 'Font Size',
      'tabulation': 'Tabulation',
      'support': 'Support',
      'telegram_channel': 'Telegram Channel',
      'telegram_chat': 'Telegram Chat',
      'report_bug': 'Report Bug',
      'legal': 'Legal Information',
      'privacy_policy': 'Privacy Policy',
      'terms': 'Terms of Service',
      'about': 'About',
      'name': 'Name',
      'version': 'Version',
      'developer': 'Developer',
      'exit': 'Exit',
      'language': 'Interface Language',
      'save': 'Save',
      'run': 'Run',
      'output_ready': 'Ready to execute',
      'executing': 'Executing...',
      'connected': 'Connected',
      'disconnected': 'Disconnected',
      'no_internet': 'No internet connection',
      'error': 'Error',
      'success': 'Success',
      'cancel': 'Cancel',
      'close': 'Close',
      'search': 'Search',
      'replace': 'Replace',
      'replace_all': 'Replace All',
      'find': 'Find',
      'format': 'Format',
      'undo': 'Undo',
      'redo': 'Redo',
      'loading': 'Loading...',
      'home': 'Home',
      'clone': 'Clone',
      'commit_push': 'Commit & Push',
      'git': 'Git',
      'web_preview': 'Web Preview',
      'no_servers': 'No servers available',
      'refresh': 'Refresh',
      'delete': 'Delete',
      'rename': 'Rename',
      'create_folder': 'Create folder',
      'create_file': 'Create file',
      'file_actions': 'Actions for',
      'opening': 'Opening',
      'in_development': 'in development',
      'copy': 'Copy',
      'clear': 'Clear',
      'copying': 'Copying in development',
      'clearing': 'Clearing output in development',
      'formatting': 'Code formatting in development',
      'searching': 'Search in development',
      'find_replace': 'Find and Replace',
      'replace_hint': 'Replace with...',
      'find_hint': 'Find...',
      'matches_found': 'matches found',
      'replace_one': 'Replace',
      'replace_all_btn': 'Replace All',
      'cancel_replace': 'Cancel replace',
      'undo_hint': 'Undo (Ctrl+Z)',
      'redo_hint': 'Redo (Ctrl+Y)',
      'done': 'Done',
      'select_language': 'Select language / Выберите язык',
      'language_changed': 'Language changed to',
      'file_saved': 'File saved',
      'file_saved_msg': 'File saved',
      'clone_success': 'Repository successfully cloned',
      'clone_error': 'Clone error',
      'commit_error': 'Commit error',
      'push_success': 'Code pushed to repository',
      'push_error': 'Push error',
      'clone_first': 'Clone repository first',
      'git_not_installed': 'Git not installed on device',
      'code_ready': 'Ready to execute',
      'executing_code': 'Executing...',
      'execution_success': 'Program executed successfully',
      'execution_error': 'Execution error',
      'html_ready': 'HTML code ready for Web Preview',
      'cloud_error': 'Server error',
      'connection_error': 'Connection error',
      'unknown_error': 'Unknown error',
      'line': 'Lines',
      'language_label': 'Language:',
      'output_label': 'Output:',
      'general': 'General',
      'about_app': 'About',
      'privacy_title': 'Privacy Policy',
      'terms_title': 'Terms of Service',
    },
  };

  static const Map<String, Map<String, String>> languageDescriptions = {
    'ru': {
      'python': 'AI, веб, наука о данных',
      'c': 'Операционные системы и железо',
      'cpp': 'Игры и высоконагруженные системы',
      'java': 'Корпоративная разработка и Android',
      'csharp': 'Windows-приложения и Unity',
      'js': 'Веб-разработка и серверы',
      'vb': 'Классические Windows-приложения',
      'sql': 'Работа с базами данных',
      'r': 'Статистика и научные исследования',
      'rust': 'Безопасные высоконагруженные системы',
    },
    'en': {
      'python': 'AI, web, data science',
      'c': 'Operating systems and hardware',
      'cpp': 'Games and high-performance systems',
      'java': 'Enterprise development and Android',
      'csharp': 'Windows apps and Unity',
      'js': 'Web development and servers',
      'vb': 'Classic Windows applications',
      'sql': 'Database management',
      'r': 'Statistics and scientific research',
      'rust': 'Safe high-performance systems',
    },
  };

  static const Map<String, String> privacyPolicyTranslations = {
    'ru': 'ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ Vorxy Code Editor\n\nДата вступления в силу: 1 сентября 2026 года\n\n1. Введение\n\nНастоящая Политика конфиденциальности описывает, как компания GOSTOWN Co. собирает, использует и защищает информацию, которую вы предоставляете при использовании мобильного приложения Vorxy Code Editor (далее — «Приложение»).\n\nМы уважаем вашу конфиденциальность и обязуемся защищать ваши персональные данные.\n\n2. Какую информацию мы собираем\n\nПриложение Vorxy Code Editor работает полностью без интернета и не собирает ваши персональные данные. Мы не запрашиваем, не храним и не передаём информацию о вас третьим лицам.\n\nПри использовании Приложения:\n- Код и файлы: Весь ваш код и созданные файлы хранятся локально на вашем устройстве. Мы не имеем доступа к ним.\n- Настройки: Ваши настройки (тема, размер шрифта и т.д.) сохраняются локально на вашем устройстве.\n- Персональные данные: Мы не запрашиваем ваше имя, адрес электронной почты, номер телефона или любую другую личную информацию.\n\n3. Как мы используем вашу информацию\n\nПоскольку мы не собираем вашу информацию, мы не используем её ни для каких целей.\n\n4. Передача данных третьим лицам\n\nМы не передаём, не продаём и не обмениваем вашу информацию с третьими лицами.\n\n5. Хранение данных\n\nВсе ваши данные (код, файлы, настройки) хранятся исключительно на вашем устройстве. Вы можете в любой момент удалить их, удалив Приложение или очистив его данные в настройках устройства.\n\n6. Безопасность\n\nМы принимаем все разумные меры для защиты данных, хранящихся на вашем устройстве. Однако помните, что ни один метод передачи или хранения данных не является на 100% безопасным.\n\n7. Ссылки на сторонние ресурсы\n\nПриложение может содержать ссылки на внешние ресурсы (например, Telegram-канал). Мы не несём ответственности за политику конфиденциальности этих ресурсов.\n\n8. Изменения в Политике конфиденциальности\n\nМы оставляем за собой право обновлять настоящую Политику конфиденциальности. Мы уведомим вас об изменениях, опубликовав новую версию в Приложении.\n\n9. Контакты\n\nПо всем вопросам, связанным с Политикой конфиденциальности, вы можете связаться с нами:\n\n- Email: vorxygtn@mail.ru\n- Telegram: https://t.me/VorxyCodeEditor',
    'en': 'PRIVACY POLICY Vorxy Code Editor\n\nEffective Date: September 1, 2026\n\n1. Introduction\n\nThis Privacy Policy describes how GOSTOWN Co. collects, uses and protects the information you provide when using the Vorxy Code Editor mobile application (hereinafter referred to as the "Application").\n\nWe respect your privacy and are committed to protecting your personal data.\n\n2. What information we collect\n\nThe Vorxy Code Editor application works completely without internet and does not collect your personal data. We do not request, store or transfer information about you to third parties.\n\nWhen using the Application:\n- Code and files: All your code and created files are stored locally on your device. We do not have access to them.\n- Settings: Your settings (theme, font size, etc.) are saved locally on your device.\n- Personal data: We do not ask for your name, email address, phone number or any other personal information.\n\n3. How we use your information\n\nSince we do not collect your information, we do not use it for any purposes.\n\n4. Transfer of data to third parties\n\nWe do not transfer, sell or exchange your information with third parties.\n\n5. Data storage\n\nAll your data (code, files, settings) is stored exclusively on your device. You can delete them at any time by deleting the Application or clearing its data in your device settings.\n\n6. Security\n\nWe take all reasonable measures to protect data stored on your device. However, remember that no method of transmission or storage of data is 100% secure.\n\n7. Links to third party resources\n\nThe Application may contain links to external resources (for example, a Telegram channel). We are not responsible for the privacy policies of these resources.\n\n8. Changes to the Privacy Policy\n\nWe reserve the right to update this Privacy Policy. We will notify you of changes by posting a new version in the Application.\n\n9. Contacts\n\nFor all questions related to the Privacy Policy, you can contact us:\n\n- Email: vorxygtn@mail.ru\n- Telegram: https://t.me/VorxyCodeEditor',
  };

  static const Map<String, String> termsTranslations = {
    'ru': 'ПОЛЬЗОВАТЕЛЬСКОЕ СОГЛАШЕНИЕ Vorxy Code Editor\n\nДата вступления в силу: 1 сентября 2026 года\n\n1. Общие положения\n\n1.1. Настоящее Пользовательское соглашение регулирует отношения между компанией GOSTOWN Co. и пользователем мобильного приложения Vorxy Code Editor (далее — «Приложение»).\n\n1.2. Использование Приложения означает полное и безоговорочное принятие условий настоящего Соглашения.\n\n2. Функционал Приложения\n\n2.1. Приложение предоставляет пользователю возможность:\n- Писать и редактировать код на 10 языках программирования.\n- Сохранять и открывать файлы локально на устройстве.\n- Запускать код (локально для 9 языков, облачно для 1).\n- Управлять файлами и папками.\n- Настраивать внешний вид и поведение редактора.\n\n3. Права и обязанности пользователя\n\n3.1. Пользователь обязуется:\n- Использовать Приложение в соответствии с его функциональным назначением.\n- Не использовать Приложение для создания вредоносного кода или ПО.\n- Не нарушать законодательство страны проживания.\n\n3.2. Пользователь имеет право:\n- Бесплатно использовать все функции Приложения.\n- Сохранять свой код и файлы локально.\n- Обращаться в поддержку по вопросам работы Приложения.\n\n4. Права и обязанности Правообладателя\n\n4.1. Правообладатель обязуется:\n- Предоставлять доступ к Приложению и его функциям.\n- Исправлять выявленные ошибки и улучшать Приложение.\n- Обеспечивать работу каналов связи (почта, Telegram).\n\n4.2. Правообладатель имеет право:\n- Вносить изменения в функционал Приложения.\n- Обновлять настоящее Соглашение с уведомлением пользователей.\n\n5. Ограничение ответственности\n\n5.1. Приложение предоставляется «как есть». Правообладатель не гарантирует, что Приложение будет работать без ошибок и сбоев.\n\n5.2. Правообладатель не несёт ответственности за:\n- Потерю данных, произошедшую по вине пользователя.\n- Ущерб, причинённый использованию Приложения.\n- Работу сторонних сервисов (облачных компиляторов, Telegram).\n\n6. Интеллектуальная собственность\n\n6.1. Код Приложения и его дизайн являются интеллектуальной собственностью Правообладателя.\n\n6.2. Пользователь сохраняет все права на свой код и файлы, созданные с помощью Приложения.\n\n7. Заключительные положения\n\n7.1. Настоящее Соглашение вступает в силу с момента первого использования Приложения.\n\n7.2. Все споры решаются в соответствии с законодательством страны регистрации Правообладателя.\n\n8. Контакты\n\n- Email: vorxygtn@mail.ru\n- Telegram: https://t.me/VorxyCodeEditor',
    'en': 'TERMS OF SERVICE Vorxy Code Editor\n\nEffective Date: September 1, 2026\n\n1. General Provisions\n\n1.1. This Terms of Service governs the relationship between GOSTOWN Co. and the user of the Vorxy Code Editor mobile application (hereinafter referred to as the "Application").\n\n1.2. Use of the Application constitutes full and unconditional acceptance of the terms of this Agreement.\n\n2. Functionality of the Application\n\n2.1. The Application provides the user with the ability to:\n- Write and edit code in 10 programming languages.\n- Save and open files locally on the device.\n- Run code (locally for 9 languages, cloud for 1).\n- Manage files and folders.\n- Customize the appearance and behavior of the editor.\n\n3. Rights and obligations of the user\n\n3.1. The user undertakes to:\n- Use the Application in accordance with its functional purpose.\n- Not use the Application to create malicious code or software.\n- Not violate the laws of the country of residence.\n\n3.2. The user has the right to:\n- Use all features of the Application for free.\n- Save your code and files locally.\n- Contact support regarding the operation of the Application.\n\n4. Rights and obligations of the Copyright Holder\n\n4.1. The Copyright Holder undertakes to:\n- Provide access to the Application and its functions.\n- Correct identified errors and improve the Application.\n- Ensure the operation of communication channels (email, Telegram).\n\n4.2. The Copyright Holder has the right to:\n- Make changes to the functionality of the Application.\n- Update this Agreement with notification to users.\n\n5. Limitation of liability\n\n5.1. The Application is provided "as is". The Copyright Holder does not guarantee that the Application will operate without errors and failures.\n\n5.2. The Copyright Holder is not responsible for:\n- Loss of data caused by the user's fault.\n- Damage caused by the use of the Application.\n- Operation of third-party services (cloud compilers, Telegram).\n\n6. Intellectual property\n\n6.1. The Application code and its design are the intellectual property of the Copyright Holder.\n\n6.2. The user retains all rights to their code and files created using the Application.\n\n7. Final provisions\n\n7.1. This Agreement comes into force from the moment of first use of the Application.\n\n7.2. All disputes are resolved in accordance with the legislation of the country of registration of the Copyright Holder.\n\n8. Contacts\n\n- Email: vorxygtn@mail.ru\n- Telegram: https://t.me/VorxyCodeEditor',
  };

  static String getPrivacyPolicy(String langCode) {
    return privacyPolicyTranslations[langCode] ?? privacyPolicyTranslations['ru']!;
  }

  static String getTerms(String langCode) {
    return termsTranslations[langCode] ?? termsTranslations['ru']!;
  }
}
