static const Map<String, Map<String, String>> languageDescriptions = {
  'ru': {
    'python': 'AI, веб, наука о данных',
    'c': 'Операционные системы и железо',
    'cpp': 'Игры и высоконагруженные системы',
    'java': 'Корпоративная разработка и Android',
    'csharp': 'Windows-приложения и Unity',
    'js': 'Веб-разработка и серверы',
    'vb': 'Классические Windows-приложения',
    'sql': 'Работа с базами данных',
    'r': 'Статистика и научные исследования',
    'rust': 'Безопасные высоконагруженные системы',
  },
  'en': {
    'python': 'AI, web, data science',
    'c': 'Operating systems and hardware',
    'cpp': 'Games and high-performance systems',
    'java': 'Enterprise development and Android',
    'csharp': 'Windows apps and Unity',
    'js': 'Web development and servers',
    'vb': 'Classic Windows applications',
    'sql': 'Database management',
    'r': 'Statistics and scientific research',
    'rust': 'Safe high-performance systems',
  },
  'uk': {
    'python': 'ШІ, веб, наука про дані',
    'c': 'Операційні системи та залізо',
    'cpp': 'Ігри та високонавантажені системи',
    'java': 'Корпоративна розробка та Android',
    'csharp': 'Windows-додатки та Unity',
    'js': 'Веб-розробка та сервери',
    'vb': 'Класичні Windows-додатки',
    'sql': 'Робота з базами даних',
    'r': 'Статистика та наукові дослідження',
    'rust': 'Безпечні високонавантажені системи',
  },
  'es': {
    'python': 'IA, web, ciencia de datos',
    'c': 'Sistemas operativos y hardware',
    'cpp': 'Juegos y sistemas de alto rendimiento',
    'java': 'Desarrollo empresarial y Android',
    'csharp': 'Aplicaciones Windows y Unity',
    'js': 'Desarrollo web y servidores',
    'vb': 'Aplicaciones clásicas de Windows',
    'sql': 'Gestión de bases de datos',
    'r': 'Estadística e investigación científica',
    'rust': 'Sistemas seguros de alto rendimiento',
  },
  'fr': {
    'python': 'IA, web, science des données',
    'c': 'Systèmes d\'exploitation et matériel',
    'cpp': 'Jeux et systèmes haute performance',
    'java': 'Développement d\'entreprise et Android',
    'csharp': 'Applications Windows et Unity',
    'js': 'Développement web et serveurs',
    'vb': 'Applications Windows classiques',
    'sql': 'Gestion de bases de données',
    'r': 'Statistiques et recherche scientifique',
    'rust': 'Systèmes haute performance sécurisés',
  },
  'de': {
    'python': 'KI, Web, Datenwissenschaft',
    'c': 'Betriebssysteme und Hardware',
    'cpp': 'Spiele und Hochleistungssysteme',
    'java': 'Unternehmensentwicklung und Android',
    'csharp': 'Windows-Apps und Unity',
    'js': 'Webentwicklung und Server',
    'vb': 'Klassische Windows-Anwendungen',
    'sql': 'Datenbankverwaltung',
    'r': 'Statistik und wissenschaftliche Forschung',
    'rust': 'Sichere Hochleistungssysteme',
  },
  'zh': {
    'python': '人工智能、网络、数据科学',
    'c': '操作系统和硬件',
    'cpp': '游戏和高性能系统',
    'java': '企业开发和Android',
    'csharp': 'Windows应用和Unity',
    'js': 'Web开发和服务器',
    'vb': '经典Windows应用',
    'sql': '数据库管理',
    'r': '统计和科学研究',
    'rust': '安全的高性能系统',
  },
  'ja': {
    'python': 'AI、ウェブ、データサイエンス',
    'c': 'オペレーティングシステムとハードウェア',
    'cpp': 'ゲームとハイパフォーマンスシステム',
    'java': 'エンタープライズ開発とAndroid',
    'csharp': 'WindowsアプリとUnity',
    'js': 'ウェブ開発とサーバー',
    'vb': 'クラシックWindowsアプリ',
    'sql': 'データベース管理',
    'r': '統計と科学研究',
    'rust': '安全なハイパフォーマンスシステム',
  },
  'ko': {
    'python': 'AI, 웹, 데이터 과학',
    'c': '운영체제 및 하드웨어',
    'cpp': '게임 및 고성능 시스템',
    'java': '엔터프라이즈 개발 및 Android',
    'csharp': 'Windows 앱 및 Unity',
    'js': '웹 개발 및 서버',
    'vb': '클래식 Windows 애플리케이션',
    'sql': '데이터베이스 관리',
    'r': '통계 및 과학 연구',
    'rust': '안전한 고성능 시스템',
  },
  'pt': {
    'python': 'IA, web, ciência de dados',
    'c': 'Sistemas operacionais e hardware',
    'cpp': 'Jogos e sistemas de alto desempenho',
    'java': 'Desenvolvimento empresarial e Android',
    'csharp': 'Aplicativos Windows e Unity',
    'js': 'Desenvolvimento web e servidores',
    'vb': 'Aplicativos Windows clássicos',
    'sql': 'Gerenciamento de banco de dados',
    'r': 'Estatística e pesquisa científica',
    'rust': 'Sistemas seguros de alto desempenho',
  },
  'it': {
    'python': 'AI, web, data science',
    'c': 'Sistemi operativi e hardware',
    'cpp': 'Giochi e sistemi ad alte prestazioni',
    'java': 'Sviluppo enterprise e Android',
    'csharp': 'App Windows e Unity',
    'js': 'Sviluppo web e server',
    'vb': 'Applicazioni Windows classiche',
    'sql': 'Gestione database',
    'r': 'Statistica e ricerca scientifica',
    'rust': 'Sistemi sicuri ad alte prestazioni',
  },
  'ar': {
    'python': 'الذكاء الاصطناعي، الويب، علوم البيانات',
    'c': 'أنظمة التشغيل والأجهزة',
    'cpp': 'الألعاب والأنظمة عالية الأداء',
    'java': 'تطوير المؤسسات وأندرويد',
    'csharp': 'تطبيقات Windows ويونيتي',
    'js': 'تطوير الويب والخوادم',
    'vb': 'تطبيقات Windows الكلاسيكية',
    'sql': 'إدارة قواعد البيانات',
    'r': 'الإحصاء والبحث العلمي',
    'rust': 'أنظمة عالية الأداء وآمنة',
  },
  'hi': {
    'python': 'AI, वेब, डेटा विज्ञान',
    'c': 'ऑपरेटिंग सिस्टम और हार्डवेयर',
    'cpp': 'गेम्स और उच्च-प्रदर्शन सिस्टम',
    'java': 'एंटरप्राइज विकास और Android',
    'csharp': 'Windows ऐप्स और Unity',
    'js': 'वेब विकास और सर्वर',
    'vb': 'क्लासिक Windows अनुप्रयोग',
    'sql': 'डेटाबेस प्रबंधन',
    'r': 'सांख्यिकी और वैज्ञानिक अनुसंधान',
    'rust': 'सुरक्षित उच्च-प्रदर्शन सिस्टम',
  },
};
