class AppConstants {
  static const String appName = 'Vorxy Code Editor';
  static const String version = '3.2.0';
  static const String developer = 'GOSTOWN Co.';
  static const String telegramChannel = 'https://t.me/VorxyCodeEditor';
  static const String telegramChat = 'https://t.me/VorxyCodeEditorChat';
  static const String supportEmail = 'vorxygtn@mail.ru';

  static const List<Map<String, String>> supportedLanguages = [
    {'code': 'ru', 'name': 'Русский', 'flag': '🇷🇺'},
    {'code': 'en', 'name': 'English', 'flag': '🇬🇧'},
    {'code': 'uk', 'name': 'Українська', 'flag': '🇺🇦'},
    {'code': 'es', 'name': 'Español', 'flag': '🇪🇸'},
    {'code': 'fr', 'name': 'Français', 'flag': '🇫🇷'},
    {'code': 'de', 'name': 'Deutsch', 'flag': '🇩🇪'},
    {'code': 'zh', 'name': '简体中文', 'flag': '🇨🇳'},
    {'code': 'ja', 'name': '日本語', 'flag': '🇯🇵'},
    {'code': 'ko', 'name': '한국어', 'flag': '🇰🇷'},
    {'code': 'pt', 'name': 'Português', 'flag': '🇵🇹'},
    {'code': 'it', 'name': 'Italiano', 'flag': '🇮🇹'},
    {'code': 'ar', 'name': 'العربية', 'flag': '🇸🇦'},
    {'code': 'hi', 'name': 'हिन्दी', 'flag': '🇮🇳'},
  ];

  static const Map<String, Map<String, String>> translations = {
    'ru': {
      'app_name': 'Vorxy Code Editor',
      'settings': 'Настройки',
      'languages': 'Языки программирования',
      'editor': 'Редактор',
      'files': 'Файлы',
      'output': 'Вывод',
      'errors': 'Ошибки',
      'terminal': 'Терминал',
      'auto_save': 'Автосохранение',
      'font_size': 'Размер шрифта',
      'tabulation': 'Табуляция',
      'support': 'Поддержка',
      'telegram_channel': 'Telegram-канал',
      'telegram_chat': 'Чат Telegram',
      'report_bug': 'Сообщить об ошибке',
      'legal': 'Юридическая информация',
      'privacy_policy': 'Политика конфиденциальности',
      'terms': 'Пользовательское соглашение',
      'about': 'О приложении',
      'name': 'Название',
      'version': 'Версия',
      'developer': 'Разработчик',
      'exit': 'Выйти',
      'language': 'Язык интерфейса',
      'save': 'Сохранить',
      'run': 'Запустить',
      'output_ready': 'Готов к выполнению',
      'executing': 'Выполнение...',
      'connected': 'Подключено',
      'disconnected': 'Отключено',
      'no_internet': 'Нет интернета',
      'error': 'Ошибка',
      'success': 'Успешно',
      'cancel': 'Отмена',
      'close': 'Закрыть',
      'search': 'Поиск',
      'replace': 'Заменить',
      'replace_all': 'Заменить все',
      'find': 'Найти',
      'format': 'Форматировать',
      'undo': 'Отменить',
      'redo': 'Повторить',
      'loading': 'Загрузка...',
      'home': 'Главная',
      'clone': 'Клонировать',
      'commit_push': 'Commit & Push',
      'git': 'Git',
      'web_preview': 'Web Preview',
      'no_servers': 'Нет доступных серверов',
      'refresh': 'Обновить',
      'delete': 'Удалить',
      'rename': 'Переименовать',
      'create_folder': 'Создать папку',
      'create_file': 'Создать файл',
      'file_actions': 'Действия для',
      'opening': 'Открытие',
      'in_development': 'в разработке',
      'copy': 'Копировать',
      'clear': 'Очистить',
      'copying': 'Копирование в разработке',
      'clearing': 'Очистка вывода в разработке',
      'formatting': 'Форматирование кода в разработке',
      'searching': 'Поиск в разработке',
      'find_replace': 'Поиск и замена',
      'replace_hint': 'Заменить на...',
      'find_hint': 'Найти...',
      'matches_found': 'совпадений',
      'replace_one': 'Заменить',
      'replace_all_btn': 'Заменить все',
      'cancel_replace': 'Отменить замену',
      'undo_hint': 'Отменить (Ctrl+Z)',
      'redo_hint': 'Повторить (Ctrl+Y)',
      'done': 'Готово',
      'select_language': 'Выберите язык / Select language',
      'language_changed': 'Язык изменён на',
      'file_saved': 'Файл сохранён',
      'file_saved_msg': 'Файл сохранён',
      'clone_success': 'Репозиторий успешно клонирован',
      'clone_error': 'Ошибка клонирования',
      'commit_error': 'Ошибка коммита',
      'push_success': 'Код отправлен в репозиторий',
      'push_error': 'Ошибка пуша',
      'clone_first': 'Сначала клонируйте репозиторий',
      'git_not_installed': 'Git не установлен на устройстве',
      'code_ready': 'Готов к выполнению',
      'executing_code': 'Выполнение...',
      'execution_success': 'Программа выполнена успешно',
      'execution_error': 'Ошибка выполнения',
      'html_ready': 'HTML код готов к просмотру в Web Preview',
      'cloud_error': 'Ошибка сервера',
      'connection_error': 'Ошибка подключения',
      'unknown_error': 'Неизвестная ошибка',
      'line': 'Строк',
      'language_label': 'Язык:',
      'output_label': 'Вывод:',
      'general': 'Общие',
      'about_app': 'О приложении',
      'privacy_title': 'Политика конфиденциальности',
      'terms_title': 'Пользовательское соглашение',
      'description': 'Профессиональная мобильная среда разработки для Android',
      'features': 'Функциональные возможности',
      'system_requirements': 'Системные требования',
      'features_list': 'Редактор кода с подсветкой синтаксиса, поиск и замена, форматирование, 10 языков программирования, файловый менеджер, 13 языков интерфейса',
      'system_requirements_list': 'Android 7.0 и выше, 50 МБ свободного места',
    },
    'en': {
      'app_name': 'Vorxy Code Editor',
      'settings': 'Settings',
      'languages': 'Programming Languages',
      'editor': 'Editor',
      'files': 'Files',
      'output': 'Output',
      'errors': 'Errors',
      'terminal': 'Terminal',
      'auto_save': 'Auto Save',
      'font_size': 'Font Size',
      'tabulation': 'Tabulation',
      'support': 'Support',
      'telegram_channel': 'Telegram Channel',
      'telegram_chat': 'Telegram Chat',
      'report_bug': 'Report Bug',
      'legal': 'Legal Information',
      'privacy_policy': 'Privacy Policy',
      'terms': 'Terms of Service',
      'about': 'About',
      'name': 'Name',
      'version': 'Version',
      'developer': 'Developer',
      'exit': 'Exit',
      'language': 'Interface Language',
      'save': 'Save',
      'run': 'Run',
      'output_ready': 'Ready to execute',
      'executing': 'Executing...',
      'connected': 'Connected',
      'disconnected': 'Disconnected',
      'no_internet': 'No internet connection',
      'error': 'Error',
      'success': 'Success',
      'cancel': 'Cancel',
      'close': 'Close',
      'search': 'Search',
      'replace': 'Replace',
      'replace_all': 'Replace All',
      'find': 'Find',
      'format': 'Format',
      'undo': 'Undo',
      'redo': 'Redo',
      'loading': 'Loading...',
      'home': 'Home',
      'clone': 'Clone',
      'commit_push': 'Commit & Push',
      'git': 'Git',
      'web_preview': 'Web Preview',
      'no_servers': 'No servers available',
      'refresh': 'Refresh',
      'delete': 'Delete',
      'rename': 'Rename',
      'create_folder': 'Create folder',
      'create_file': 'Create file',
      'file_actions': 'Actions for',
      'opening': 'Opening',
      'in_development': 'in development',
      'copy': 'Copy',
      'clear': 'Clear',
      'copying': 'Copying in development',
      'clearing': 'Clearing output in development',
      'formatting': 'Code formatting in development',
      'searching': 'Search in development',
      'find_replace': 'Find and Replace',
      'replace_hint': 'Replace with...',
      'find_hint': 'Find...',
      'matches_found': 'matches found',
      'replace_one': 'Replace',
      'replace_all_btn': 'Replace All',
      'cancel_replace': 'Cancel replace',
      'undo_hint': 'Undo (Ctrl+Z)',
      'redo_hint': 'Redo (Ctrl+Y)',
      'done': 'Done',
      'select_language': 'Select language / Выберите язык',
      'language_changed': 'Language changed to',
      'file_saved': 'File saved',
      'file_saved_msg': 'File saved',
      'clone_success': 'Repository successfully cloned',
      'clone_error': 'Clone error',
      'commit_error': 'Commit error',
      'push_success': 'Code pushed to repository',
      'push_error': 'Push error',
      'clone_first': 'Clone repository first',
      'git_not_installed': 'Git not installed on device',
      'code_ready': 'Ready to execute',
      'executing_code': 'Executing...',
      'execution_success': 'Program executed successfully',
      'execution_error': 'Execution error',
      'html_ready': 'HTML code ready for Web Preview',
      'cloud_error': 'Server error',
      'connection_error': 'Connection error',
      'unknown_error': 'Unknown error',
      'line': 'Lines',
      'language_label': 'Language:',
      'output_label': 'Output:',
      'general': 'General',
      'about_app': 'About',
      'privacy_title': 'Privacy Policy',
      'terms_title': 'Terms of Service',
      'description': 'Professional mobile development environment for Android',
      'features': 'Features',
      'system_requirements': 'System Requirements',
      'features_list': 'Code editor with syntax highlighting, search and replace, formatting, 10 programming languages, file manager, 13 interface languages',
      'system_requirements_list': 'Android 7.0 and above, 50 MB free space',
    },
  };

  static const Map<String, Map<String, String>> languageDescriptions = {
    'ru': {
      'python': 'AI, веб, наука о данных',
      'c': 'Операционные системы и железо',
      'cpp': 'Игры и высоконагруженные системы',
      'java': 'Корпоративная разработка и Android',
      'csharp': 'Windows-приложения и Unity',
      'js': 'Веб-разработка и серверы',
      'vb': 'Классические Windows-приложения',
      'sql': 'Работа с базами данных',
      'r': 'Статистика и научные исследования',
      'rust': 'Безопасные высоконагруженные системы',
    },
    'en': {
      'python': 'AI, web, data science',
      'c': 'Operating systems and hardware',
      'cpp': 'Games and high-performance systems',
      'java': 'Enterprise development and Android',
      'csharp': 'Windows apps and Unity',
      'js': 'Web development and servers',
      'vb': 'Classic Windows applications',
      'sql': 'Database management',
      'r': 'Statistics and scientific research',
      'rust': 'Safe high-performance systems',
    },
  };

  static const Map<String, String> privacyPolicyTranslations = {
    'ru': 'ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ Vorxy Code Editor. Дата вступления в силу: 1 сентября 2026 года. 1. Введение. Настоящая Политика конфиденциальности описывает, как компания GOSTOWN Co. собирает, использует и защищает информацию, которую вы предоставляете при использовании мобильного приложения Vorxy Code Editor. Мы уважаем вашу конфиденциальность и обязуемся защищать ваши персональные данные. 2. Какую информацию мы собираем. Приложение Vorxy Code Editor работает полностью без интернета и не собирает ваши персональные данные. Мы не запрашиваем, не храним и не передаём информацию о вас третьим лицам. При использовании Приложения: Код и файлы хранятся локально на вашем устройстве. Мы не имеем доступа к ним. Настройки сохраняются локально на вашем устройстве. Персональные данные не запрашиваются. 3. Как мы используем вашу информацию. Поскольку мы не собираем вашу информацию, мы не используем её ни для каких целей. 4. Передача данных третьим лицам. Мы не передаём, не продаём и не обмениваем вашу информацию с третьими лицами. 5. Хранение данных. Все ваши данные хранятся исключительно на вашем устройстве. 6. Безопасность. Мы принимаем все разумные меры для защиты данных. 7. Ссылки на сторонние ресурсы. Приложение может содержать ссылки на внешние ресурсы. 8. Изменения в Политике конфиденциальности. Мы оставляем за собой право обновлять настоящую Политику. 9. Контакты. Email: vorxygtn@mail.ru, Telegram: https://t.me/VorxyCodeEditor',
    'en': 'PRIVACY POLICY Vorxy Code Editor. Effective Date: September 1, 2026. 1. Introduction. This Privacy Policy describes how GOSTOWN Co. collects, uses and protects the information you provide when using the Vorxy Code Editor mobile application. We respect your privacy and are committed to protecting your personal data. 2. What information we collect. The Vorxy Code Editor application works completely without internet and does not collect your personal data. We do not request, store or transfer information about you to third parties. When using the Application: Code and files are stored locally on your device. Settings are saved locally on your device. Personal data is not requested. 3. How we use your information. Since we do not collect your information, we do not use it for any purposes. 4. Transfer of data to third parties. We do not transfer, sell or exchange your information with third parties. 5. Data storage. All your data is stored exclusively on your device. 6. Security. We take all reasonable measures to protect data. 7. Links to third party resources. The Application may contain links to external resources. 8. Changes to the Privacy Policy. We reserve the right to update this Privacy Policy. 9. Contacts. Email: vorxygtn@mail.ru, Telegram: https://t.me/VorxyCodeEditor',
  };

  static const Map<String, String> termsTranslations = {
    'ru': 'ПОЛЬЗОВАТЕЛЬСКОЕ СОГЛАШЕНИЕ Vorxy Code Editor. Дата вступления в силу: 1 сентября 2026 года. 1. Общие положения. Настоящее Пользовательское соглашение регулирует отношения между компанией GOSTOWN Co. и пользователем мобильного приложения Vorxy Code Editor. Использование Приложения означает полное и безоговорочное принятие условий настоящего Соглашения. 2. Функционал Приложения. Приложение предоставляет пользователю возможность писать и редактировать код на 10 языках программирования, сохранять и открывать файлы локально на устройстве, управлять файлами и папками, настраивать внешний вид и поведение редактора. 3. Права и обязанности пользователя. Пользователь обязуется использовать Приложение в соответствии с его функциональным назначением, не использовать Приложение для создания вредоносного кода или ПО, не нарушать законодательство страны проживания. Пользователь имеет право бесплатно использовать все функции Приложения, сохранять свой код и файлы локально, обращаться в поддержку. 4. Права и обязанности Правообладателя. Правообладатель обязуется предоставлять доступ к Приложению и его функциям, исправлять выявленные ошибки и улучшать Приложение, обеспечивать работу каналов связи. Правообладатель имеет право вносить изменения в функционал Приложения и обновлять Соглашение. 5. Ограничение ответственности. Приложение предоставляется как есть. Правообладатель не гарантирует, что Приложение будет работать без ошибок и сбоев. Правообладатель не несёт ответственности за потерю данных, ущерб, работу сторонних сервисов. 6. Интеллектуальная собственность. Код Приложения и его дизайн являются интеллектуальной собственностью Правообладателя. Пользователь сохраняет все права на свой код и файлы. 7. Заключительные положения. Соглашение вступает в силу с момента первого использования Приложения. Все споры решаются в соответствии с законодательством страны регистрации Правообладателя. 8. Контакты. Email: vorxygtn@mail.ru, Telegram: https://t.me/VorxyCodeEditor',
    'en': 'TERMS OF SERVICE Vorxy Code Editor. Effective Date: September 1, 2026. 1. General Provisions. This Terms of Service governs the relationship between GOSTOWN Co. and the user of the Vorxy Code Editor mobile application. Use of the Application constitutes full and unconditional acceptance of the terms of this Agreement. 2. Functionality of the Application. The Application provides the user with the ability to write and edit code in 10 programming languages, save and open files locally on the device, manage files and folders, customize the appearance and behavior of the editor. 3. Rights and obligations of the user. The user undertakes to use the Application in accordance with its functional purpose, not to use the Application to create malicious code or software, not to violate the laws of the country of residence. The user has the right to use all features of the Application for free, save code and files locally, contact support. 4. Rights and obligations of the Copyright Holder. The Copyright Holder undertakes to provide access to the Application and its functions, correct identified errors and improve the Application, ensure the operation of communication channels. The Copyright Holder has the right to make changes to the functionality of the Application and update this Agreement. 5. Limitation of liability. The Application is provided as is. The Copyright Holder does not guarantee that the Application will operate without errors and failures. The Copyright Holder is not responsible for loss of data, damage, operation of third-party services. 6. Intellectual property. The Application code and its design are the intellectual property of the Copyright Holder. The user retains all rights to their code and files. 7. Final provisions. This Agreement comes into force from the moment of first use of the Application. All disputes are resolved in accordance with the legislation of the country of registration of the Copyright Holder. 8. Contacts. Email: vorxygtn@mail.ru, Telegram: https://t.me/VorxyCodeEditor',
  };

  static String getPrivacyPolicy(String langCode) {
    return privacyPolicyTranslations[langCode] ?? privacyPolicyTranslations['ru']!;
  }

  static String getTerms(String langCode) {
    return termsTranslations[langCode] ?? termsTranslations['ru']!;
  }
}
